spring:
  flyway:
    locations: ["classpath:flyway"]
  datasource:
    url: jdbc:postgresql://localhost:5432/r2dbc
    host: localhost
    port: 5432
    username: hejwo
    password: EeV5eiva
    database: r2dbc