scrape_configs:
- job_name: 'prometheus'
  metrics_path: '/metrics'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'backend'
  metrics_path: '/metrics/prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['backend:8888']

- job_name: 'cadvisor'
  scrape_interval: 5s
  static_configs:
  - targets: ['cadvisor:8080']

# postgres scrape